export default {
    greaterThan: {
        _initial: true,
        lg: false,
        md: false,
        sm: true,
        xl: false,
        xs: true,
    },
    is: {
        _initial: false,
        lg: false,
        md: true,
        sm: false,
        xl: false,
        xs: false,
    },
    isCalculated: true,
    lessThan: {
        _initial: false,
        lg: true,
        md: false,
        sm: false,
        xl: true,
        xs: false,
    },
    mediaType: 'md',
    mobileBreakpoint: 'md',
    orientation: 'landscape',
};
